language: python

python:
- 3.5
- 3.6
- 3.7
- 3.8

dist: bionic

install:
  - python -m pip install -U pip wheel setuptools
  - python -m pip install -Ur requirements.txt
  
script:
  # build the wheels, put them into './wheelhouse'
  #- python -m cibuildwheel --output-dir wheelhouse
  - python3 -c "print('Hello World')"
  - python3 -c "import platform;print(platform.python_version())"
  - python3 -c "import platform;print(platform.python_compiler())"
  - python3 -c "import platform;print(platform.uname())"
  - git submodule update --init
  - cibuildwheel --platform auto --output-dir Slycot_wheel Slycot/
